export const rows = [
    {
        id: 1,
        '#': 71,
        position: 'PG',
        name: 'W. Tran',
        points: '2',
        assists: '4',
        rebounds: '1',
        '+/-': 4,
    },
    {
        id: 2,
        '#': 15,
        position: 'SG',
        name: 'M. Hoffman',
        points: '12',
        assists: '4',
        rebounds: '1',
        '+/-': 4,
    },
    {
        id: 3,
        '#': 10,
        position: 'SG',
        name: 'T. Valdez',
        points: '8',
        assists: '1',
        rebounds: '3',
        '+/-': 4,
    },
    {
        id: 4,
        '#': 2,
        position: 'PF',
        name: 'H. Austin',
        points: '0',
        assists: '1',
        rebounds: '5',
        '+/-': 8,
    },
    {
        id: 5,
        '#': 35,
        position: 'SF',
        name: 'D. Berry',
        points: '4',
        assists: '1',
        rebounds: '0',
        '+/-': 8,
    },
    {
        id: 6,
        '#': 13,
        position: 'C',
        name: 'J. Butler',
        points: '2',
        assists: '1',
        rebounds: '8',
        '+/-': 8,
    },
    {
        id: 1,
        '#': 19,
        position: 'C',
        name: 'J. Chapman',
        points: '8',
        assists: '1',
        rebounds: '8',
        '+/-': 8,
    },
];
