# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
    components-chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn
            - name: Build components storybook
              run: npx nx run components:build-storybook
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  storybookBuildDir: 'dist/storybook/components'
