# Run interaction tests with Jest

name: 'edene library CI'

on: [push, pull_request]

jobs:
    # Run interaction tests with Jest
    interaction:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn
            - name: Run tests
              run: npx nx run edene:test
