name: 'Edene Changelog CI'

on:
    push:
        tags:
            - '*'

jobs:
    publish-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Update CHANGELOG
              id: changelog
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ github.token }}
                  tag: ${{ github.ref_name }}

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  draft: false
                  name: ${{ github.ref_name }}
                  body: ${{ steps.changelog.outputs.changes }}
                  token: ${{ github.token }}

            - name: Commit CHANGELOG.md
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: main
                  commit_message: 'chore: Release ${{ github.ref_name }}'
                  commit_options: '--amend --no-edit'
                  push_options: '--force'
                  file_pattern: CHANGELOG.md
